version: "3.9"

services:
  api:
    image: aryu_api:latest
    container_name: aryu_api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  redis:
    image: redis:7
    container_name: aryu_redis
    restart: always

  db:
    image: postgres:15
    container_name: aryu_db
    restart: always
    environment:
      POSTGRES_DB: aryu_db
      POSTGRES_USER: aryu_user
      POSTGRES_PASSWORD: STRONG_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
